### ISSUE TITLE
How does it work? sample-confi.json?

### ISSUE THREAD

**Issue by 420Dope** [KisonBY/homebrigde-http-watcher-switch#1]
Hey,
i really like the idea of this plugin. But how does it works? I can´t find a sample-config.json file so i can not add it to the accessories in the config.json.

When i start homebridge i have this in the log:
```
[2018-11-3 12:50:09] ---
[2018-11-3 12:50:09] Loaded plugin: homebridge-http-watcher-switch
Failed to open plugin configuration, default settings will be used! { Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\.homebridge\homebridge-http-watcher-switch\config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Plugin.module.exports [as initializer] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-http-watcher-switch\index.js:24:38)
    at Server.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:167:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:141:22)
    at new Server (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:57:24)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:30:16)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:643:30)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Administrator\\.homebridge\\homebridge-http-watcher-switch\\config.json' }
Starting HTTP listener on port 3001...
HTTP listener started.
[2018-11-3 12:50:09] Registering accessory 'homebridge-http-watcher-switch.HttpWatcherSwitch'
[2018-11-3 12:50:09] ---
ˋˋˋ

**Comment by KisonBY** [comment]
@420Dope, thanks for your interest. Unfortunately, I have abandoned this development over a year ago and currently don't even have it running (gotta undust my Raspberry Pi with Homebridge setup).

Anyway, there is a fork of this project that has some enhancements and more importantly, a proper readme.md with a sample configuration. Please take a look here: https://github.com/jnvaldenaire/homebridge-http-programmableswitch

**Comment by 420Dope** [comment]
Thank you very much for the hint.
